/// The identity of the current puzzle generator.
///
/// A saved puzzle is stored as an ID, not as a grid, so the generator that
/// turns an ID back into a grid is part of the save format. Bumping this
/// version means "the same ID now produces a different puzzle", which
/// invalidates every stored ID generated by an earlier version.
///
/// So a bump comes with three things, together, in the same change:
///
/// 1. regenerated golden files (`test/golden/`),
/// 2. the previous generator kept reachable behind this switch, and
/// 3. a migration that reads saves written by the old version.
///
/// If a change to generation is not intended to alter output — a refactor, a
/// speed-up — the golden tests prove it, and this version stays put.
const int generatorVersion = 1;
